name: TEST

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: CouchDB ${{ matrix.couchdb }}
    runs-on: ubuntu-latest
    timeout-minutes: 15

    strategy:
      fail-fast: false
      matrix:
        couchdb: [latest, "3.4", "3.3", "3.2", "3.1", "2.3"]

    steps:
      - name: Clone Repository
        uses: actions/checkout@v2

      - name: Start CouchDB
        uses: ./
        with:
          couchdb-version: ${{ matrix.couchdb }}

      - name: Test
        run: curl -sS -f http://127.0.0.1:5984/
